-- PART 02 — initial schema for the LexHack backend.
--
-- Conventions used throughout this schema:
--   * Primary keys are UUIDs generated by `gen_random_uuid()`
--     (built into PostgreSQL 13+; we require PostgreSQL 13 or newer).
--   * All timestamps are `TIMESTAMPTZ` and stored in UTC.
--   * Controlled vocabularies (risk level, status, channel, ...) are
--     represented as `TEXT` with a `CHECK` constraint rather than as
--     PostgreSQL `ENUM` types. PostgreSQL ENUMs cannot have values removed,
--     only added, and they make routine changes (renaming, extending,
--     splitting) painful. `TEXT + CHECK` gives us the same database-level
--     protection with a migration path that does not require a type
--     rewrite. See `docs/DATABASE.md` for the full rationale.
--   * Foreign keys are deliberately `ON DELETE CASCADE` where the child
--     row has no meaning without its parent (a contract without a user, an
--     obligation without a contract, ...). This is documented per-table
--     below.

-- =========================================================================
-- users
-- =========================================================================

CREATE TABLE users (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email           TEXT        NOT NULL,
    password_hash   TEXT        NOT NULL,
    full_name       TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT users_email_unique           UNIQUE (email),
    CONSTRAINT users_email_not_empty        CHECK (length(btrim(email)) > 0),
    CONSTRAINT users_email_shape            CHECK (
        email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
    ),
    CONSTRAINT users_password_hash_not_empty CHECK (length(password_hash) > 0),
    CONSTRAINT users_full_name_not_empty    CHECK (length(btrim(full_name)) > 0)
);

-- =========================================================================
-- contracts
-- =========================================================================

CREATE TABLE contracts (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           TEXT        NOT NULL,
    raw_text        TEXT        NOT NULL,
    start_date      DATE,
    end_date        DATE,
    risk_level      TEXT,
    risk_score      INTEGER,
    risk_summary    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT contracts_title_not_empty    CHECK (length(btrim(title)) > 0),
    CONSTRAINT contracts_title_max_length   CHECK (length(title) <= 500),
    CONSTRAINT contracts_raw_text_not_empty CHECK (length(btrim(raw_text)) > 0),
    CONSTRAINT contracts_risk_level_valid   CHECK (
        risk_level IS NULL
        OR risk_level IN ('low', 'medium', 'high', 'critical')
    ),
    CONSTRAINT contracts_risk_score_range   CHECK (
        risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)
    ),
    CONSTRAINT contracts_dates_ordered      CHECK (
        start_date IS NULL OR end_date IS NULL OR start_date <= end_date
    )
);

-- =========================================================================
-- contract_obligations
-- =========================================================================

CREATE TABLE contract_obligations (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id         UUID        NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    title               TEXT        NOT NULL,
    description         TEXT        NOT NULL,
    due_date            DATE,
    responsible_party   TEXT,
    status              TEXT        NOT NULL DEFAULT 'pending',
    risk_level          TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT contract_obligations_id_contract_unique UNIQUE (id, contract_id),
    CONSTRAINT obligations_title_not_empty        CHECK (length(btrim(title)) > 0),
    CONSTRAINT obligations_description_not_empty  CHECK (length(btrim(description)) > 0),
    CONSTRAINT obligations_status_valid           CHECK (
        status IN ('pending', 'completed', 'overdue', 'cancelled')
    ),
    CONSTRAINT obligations_risk_level_valid       CHECK (
        risk_level IS NULL
        OR risk_level IN ('low', 'medium', 'high', 'critical')
    )
);

-- =========================================================================
-- contract_risks
-- =========================================================================

CREATE TABLE contract_risks (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id     UUID        NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    title           TEXT        NOT NULL,
    description     TEXT        NOT NULL,
    risk_level      TEXT        NOT NULL,
    risk_score      INTEGER     NOT NULL,
    evidence        TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT risks_title_not_empty        CHECK (length(btrim(title)) > 0),
    CONSTRAINT risks_description_not_empty  CHECK (length(btrim(description)) > 0),
    CONSTRAINT risks_evidence_not_empty     CHECK (length(btrim(evidence)) > 0),
    CONSTRAINT risks_risk_level_valid       CHECK (
        risk_level IN ('low', 'medium', 'high', 'critical')
    ),
    CONSTRAINT risks_risk_score_range       CHECK (risk_score >= 0 AND risk_score <= 100)
);

-- =========================================================================
-- reminders
-- =========================================================================

CREATE TABLE reminders (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id     UUID        NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    obligation_id   UUID,
    reminder_date   TIMESTAMPTZ NOT NULL,
    reminder_type   TEXT        NOT NULL,
    channel_type    TEXT        NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'pending',
    sent_at         TIMESTAMPTZ,
    attempts        INTEGER     NOT NULL DEFAULT 0,
    last_error      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT reminders_type_valid       CHECK (
        reminder_type IN ('7_days_before', '3_days_before', '1_day_before', 'on_deadline', 'custom')
    ),
    CONSTRAINT reminders_channel_valid    CHECK (
        channel_type IN ('telegram', 'webhook', 'discord')
    ),
    CONSTRAINT reminders_status_valid     CHECK (
        status IN ('pending', 'processing', 'sent', 'failed', 'cancelled')
    ),
    CONSTRAINT reminders_attempts_non_negative CHECK (attempts >= 0),
    CONSTRAINT reminders_obligation_belongs_to_contract
        FOREIGN KEY (obligation_id, contract_id)
        REFERENCES contract_obligations (id, contract_id)
        ON DELETE CASCADE
);

-- =========================================================================
-- audit_logs
-- =========================================================================

CREATE TABLE audit_logs (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        REFERENCES users(id) ON DELETE SET NULL,
    action          TEXT        NOT NULL,
    entity_type     TEXT        NOT NULL,
    entity_id       UUID,
    metadata        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT audit_action_not_empty      CHECK (length(btrim(action)) > 0),
    CONSTRAINT audit_entity_type_not_empty CHECK (length(btrim(entity_type)) > 0)
);

-- =========================================================================
-- Indexes
-- =========================================================================

CREATE INDEX idx_contracts_user_id ON contracts (user_id);
CREATE INDEX idx_contracts_end_date ON contracts (end_date);
CREATE INDEX idx_obligations_contract_id ON contract_obligations (contract_id);
CREATE INDEX idx_obligations_due_date ON contract_obligations (due_date);
CREATE INDEX idx_obligations_status ON contract_obligations (status);
CREATE INDEX idx_risks_contract_id ON contract_risks (contract_id);
CREATE INDEX idx_reminders_contract_id ON reminders (contract_id);
CREATE INDEX idx_reminders_obligation_id ON reminders (obligation_id);
CREATE INDEX idx_reminders_status ON reminders (status);
CREATE INDEX idx_reminders_pending_due
    ON reminders (reminder_date)
    WHERE status = 'pending';
CREATE INDEX idx_audit_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_created_at ON audit_logs (created_at DESC);
